Teo-Sprint-14th-1team/cherryblossom

package-lock.json
pages/creation/index.tsx
src/components/Creation/Custom/index.tsx
src/components/Creation/Display/index.tsx
src/components/Creation/PageTitle/index.tsx

feat : add creation page

---

src/components/ToastMessage/index.tsx

feat: 토스트 메세지 기능 구현

---

pages/received/index.tsx

Feat/received 페이지 구현

---

tailwind.config.js

fix: tailwind.config 수정

---

package-lock.json
package.json
pages/_app.tsx
src/constants/defaultSEO.ts

merge : 미리보기를 위한 머지

---

pages/creation/index.tsx

- creation 페이지 -> complete 페이지 이동 주소값/쿼리 전달 형식 변경

fix: creation 페이지 -> complete 페이지 이동 주소값/쿼리 전달 형식 변경

---

next.config.js
pages/complete/[img].tsx
pages/creation/index.tsx
pages/received/[img].tsx
src/utils/index.ts

- 파이어베이스 이미지 불러오기 기능 구현 (complete, received 페이지)

feat : 파이어베이스 이미지 불러오기 기능 구현

---

pages/api/share.ts
pages/complete/[img].tsx
src/components/CompleteLayout.tsx

fix:링크 복사 주소 변경, 버튼 색 변경 추가

---

src/components/common/SEO.tsx

feat : 받을때의 사람 미리보기 임시로

---

src/components/Creation/Display/index.tsx

refactor: useEffect 관심사 분리

---

.eslintrc.json
package-lock.json
package.json
src/components/CompleteLayout.tsx
src/components/Creation/Custom/index.tsx
src/components/Creation/Display/index.tsx
src/components/Creation/PageTitle/index.tsx
src/components/InterActionCard.tsx
src/components/Layout.tsx
src/components/ToastMessage/index.tsx
src/components/common/SEO.tsx

- prettier-plugin-tailwindcss 설치
- 해당 플러그인은 테일윈드 클래스 자동정렬을 위한 플러그인입니다.
- 테일윈드 클래스 자동완성 기능은 각자 https://github.com/tailwindlabs/tailwindcss-intellisense 링크의 플러그인을 vscode 에서 설치하시면 됩니다.
- 자동정렬을 적용하기 위해 부득이하게 모든 컴포넌트가 pr 대상이 되었습니다.

Chore : tailwind 포맷팅 설정

---

package-lock.json
src/components/CompleteLayout.tsx
src/components/InterActionCard.tsx

- 카드 테두리 여백 삭제
- overflow : hidden 적용으로 부모 요소 rounded 적용 (애니메이션 카드에도 동일 적용)

fix: 카드 테두리 여백 삭제, overflow: hidden 적용

---

pages/creation/index.tsx
src/components/Creation/Custom/index.tsx
src/components/Creation/PageTitle/index.tsx

style : creation 페이지 레이아웃 수정

---

pages/creation/index.tsx
src/components/Creation/Custom/index.tsx
src/components/Creation/Display/index.tsx
styles/globals.css

https://user-images.githubusercontent.com/31424628/225012917-e725927a-fa68-4b6c-9f05-f76d9b0229d6.mov
- 드래그앤드롭 기능 완성했습니다.
- 모바일과 데스크톱 버전 모두 정상 작동합니다.
- 로컬에서만 확인한거라 배포 하고 확인 해봐야 하긴 합니다!

creation 페이지 drag & drop

---

src/components/Creation/Display/index.tsx

html2canvas에서 textarea 사용시 개행이 안되어 pre tag로 변경
-> pre tag로 변경하는 과정에서 placeholder가 사라졌습니다...!!

feat : testarea to pre tag

---

pages/creation/index.tsx
src/components/Creation/Custom/index.tsx

style : style 수정

---

pages/creation/index.tsx
src/components/Creation/Custom/index.tsx

배포를 위해서 pages/creation/index.tsx 와 src/components/Creation/Custom/index.tsx 에서 타입에러 전체를 무시했습니다. 나중에 확인후 수정바랍니다!

fix : 일단 타입 에러 무시

---

public/creation/brownBorder.svg
tailwind.config.js

초대장 보더 에러 수정했습니다!
디자인 관련해서 애나한테 수정사항이 생길수도 있는데 당장 급한 문제 해결했습니다.

[fix] 초대장 보더 에러

---

pages/_app.tsx
src/lib/gtag.js

google analytics 설정 및 추가
- 초기 세팅만 해놔서 어느정도 수준인 지 정확히 모름
- 추후 클릭 등 분석 시스템을 추가할 수 있다하는데 필요한 부분 공부해서 세팅값 추가함.

[feat] ga-config

---

pages/creation/index.tsx
src/components/Creation/Custom/index.tsx
src/components/Creation/Display/index.tsx

- 드래그 할 때 이미지가 너무 작아 안보여서 크기를 키웠습니다.
- 꾹 누를 때 context menu가 나오는 것 안나오게 작업하는 중입니다.

creation 페이지 - 드래그 시 이미지 크기 조정

---

pages/creation/index.tsx
src/components/Creation/Custom/index.tsx
src/components/Creation/Display/index.tsx

- 드래그할 때 좌표보다 아이템을 왼쪽 위에 위치하게 수정
- 드래그할 때 preview 이미지 초록색 border color 추가

feat/creation drag&drop effect

---

pages/creation/index.tsx
src/utils/index.ts

- 기존 setTimeOut 코드를 제대로 비동기 처리하게 바꿨습니다.

fix: firebase 이미지 저장 비동기 처리

---

pages/creation/index.tsx
src/components/CompleteLayout.tsx
src/components/InterActionCard.tsx
src/components/Layout.tsx
src/components/ToastMessage/index.tsx
tailwind.config.js

- 레이아웃 반응형에 맞게끔 수정
- 최대 넓이 420px 로 반영
- 360px ~ 420px 사이의 여백은 padding 으로 작용하게끔 반영함

fix: 레이아웃 반응형 수정

---

pages/creation/index.tsx
src/components/Creation/Display/index.tsx

- 초대장 완성 시 흰 배경만 나오는 에러 수정
- 드래그 시 스크롤 안되게 설정

fix : Creation 페이지

---

src/components/Creation/Display/index.tsx

feat : 전체 삭제 모달 추가

---

pages/creation/CreationComponent.tsx
pages/creation/index.tsx

- CreationComponent를 만들어 기존 creation 페이지의 index파일을 복사
- Creation page의 index파일에서는 CreationComponent를 dynamic import 하도록 변경

feat: Creation 페이지 dynamic import 적용
